config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :admin do
    resources :users do
      member do
        patch :activate
        patch :deactivate
        patch :change_role
      end
    end
    resources :surveys
    resources :dashboard, only: [:index]
  end

  resources :surveys, only: [:show] do
    member do
      post :feedback
    end
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'PisanoSurveyApp', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Admin Panel', admin_dashboard_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <span class="nav-link"><%= current_user.email %></span>
          </li>
          <li class="nav-item">
            <%= button_to 'Çıkış Yap', destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Giriş Yap', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Kayıt Ol', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 